//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using NAS.DAL.Accounting.Tax;
namespace NAS.DAL.Invoice
{

    public partial class BillTax : XPCustomObject
    {
        Guid fBillTaxId;
		[Key(true)]
        public Guid BillTaxId
        {
            get { return fBillTaxId; }
            set { SetPropertyValue<Guid>("BillTaxId", ref fBillTaxId, value); }
		}

        double fTaxInNumber;
        public double TaxInNumber
        {
            get { return fTaxInNumber; }
            set { SetPropertyValue<double>("TaxInNumber", ref fTaxInNumber, value); }
        }
        double fTaxInPercentage;
        public double TaxInPercentage
        {
            get { return fTaxInPercentage; }
            set { SetPropertyValue<double>("TaxInPercentage", ref fTaxInPercentage, value); }
        }

        Tax fTaxId;
        [Association(@"BillTaxReferencesTax")]
        public Tax TaxId
        {
            get { return fTaxId; }
            set { SetPropertyValue<Tax>("TaxId", ref fTaxId, value); }
        } 

        Bill fBillId;
        [Association(@"BillTaxReferencesBill")]
        public Bill BillId
        {
            get { return fBillId; }
            set { SetPropertyValue<Bill>("BillId", ref fBillId, value); }
        }

	}

}
