//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace NAS.DAL.CMS.ObjectDocument
{
    [MapInheritance(MapInheritanceType.OwnTable)]
    public partial class CustomFieldDataFloat : CustomFieldData
    {
        // Fields...
        private double _FloatValue;

        public double FloatValue
        {
            get
            {
                return _FloatValue;
            }
            set
            {
                SetPropertyValue("FloatValue", ref _FloatValue, value);
            }
        }
	}
}
