//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
namespace NAS.DAL.CMS.ObjectDocument
{

    public partial class CustomFieldData : XPCustomObject
    {
        Guid fCustomFieldDataId;
		[Key(true)]
        public Guid CustomFieldDataId
        {
            get { return fCustomFieldDataId; }
            set { SetPropertyValue<Guid>("CustomFieldDataId", ref fCustomFieldDataId, value); }
		}
        int fOrder;
        public int Order
        {
            get { return fOrder; }
            set { SetPropertyValue<int>("Order", ref fOrder, value); }
        }
        CustomField fCustomFieldId;
        [Association(@"CustomFieldDataReferencesCustomField")]
        public CustomField CustomFieldId
        {
            get { return fCustomFieldId; }
            set { SetPropertyValue<CustomField>("CustomFieldId", ref fCustomFieldId, value); }
        } 

        [Association(@"ObjectCustomFieldDataReferencesCustomFieldData", typeof(ObjectCustomFieldData)), Aggregated]
        public XPCollection<ObjectCustomFieldData> ObjectCustomFieldDatas { get { return GetCollection<ObjectCustomFieldData>("ObjectCustomFieldDatas"); } }

	}
}
